name: silly-sprites
on:
    workflow_dispatch:
    push:
    pull_request:
        branches: [ main ]
        
jobs:
    job:
        name: ${{matrix.build}}/${{matrix.os}}/${{github.workflow}}
        runs-on: ${{matrix.os}}
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest , windows-latest ]
                build: [ Release, Debug ]
        
        steps:
        -   name: "checkout"
            uses: actions/checkout@v3
            
        -   name: "Generate Directory"
            run: cmake -S . -B build
          
        -   name: "Build in Release"
            run: cmake --build build --config Release
            if: ${{ matrix.build == 'Release' }}
        
        -   name: "Build in Debug"
            run: cmake --build build --config Debug
            if: ${{ matrix.build == 'Debug' }}
