name: silly_sprites
on:
    push:
    pull_request:
        branches: [ main ]
        
jobs:
    job:
        name: ${{matrix.build}}-${{matrix.os}}-${{github.workflow}}
        runs-on: ${{matrix.os}}
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest , windows-latest]
                build: [Release, Debug]
        
        
        steps:
        - name: "testing first step"
          uses: actions/checkout@v3
        